### ISSUE TITLE
Found a way to install custom font to Font changer

### ISSUE THREAD

**Issue by Raviraj476** [JohnFawkes/fontchanger#15]
I did find a way but it is a little bit of work to get it but it works.

I recommend you to do this in the PC (Any OS system works except DOS lol)

-First Step - Install the normal font provided in the font changer in mobile
-Now go to file manager - Internal storage - fontchanger - fonts
-I like Aleo font so that was the first font I installed. I will base this on that font. 
Custom Font is BlackChancery.
-In the font folder, you will see two things. 1 = custom folder 2=font_aleo.zip
-Create New folder in the custom folder. Name it "Font_BlackChancery"
-Copy the font you want to convert into custom font. It should be in .ttf format.
-You will have to create 23 copy of the same font in the Font_BlackChancery folder.
-Now exact font_aleo.zip. You will see that 23 of fonts will be there in the exacted file.
-Now you will have to put the same name as the extracted files into the Custom 23 fonts.
-Now you got custom font in the terminal. 

I know its a little too much work but You don't need linux system to do this.
Just have to copy paste.

**Comment by JohnFawkes** [comment]
please dont do this. theres a reason i havent fixed custom fonts yet
