### ISSUE TITLE
Could you make it work on xiaomi phone?

### ISSUE THREAD

**Issue by woupss** [JohnFawkes/fontchanger#2]
Hi,

I use a Xiaomi Mi Mix 2s phone and i would like to use your module but i can't make it works.
When i choose the number of the font, it doesn't download itand show me this message "! Item not available - try again !".
When i want to use a custom font  all seems ok in installation but it doesn't apply to the phone.
Perhaps it's a xiaomi MIUI specific problem.

Thanks
[Fontchanger-verbose[1].log](https://github.com/JohnFawkes/fontchanger/files/3285868/Fontchanger-verbose.1.log)

**Comment by JohnFawkes** [comment]
fixed in latest version i just pushed
