### ISSUE TITLE
On custom font, 1.6 works but 1.7 does not.

### ISSUE THREAD

**Issue by yipinghuang1991** [JohnFawkes/fontchanger#3]
It seems like custom fonts are bind-mounted to /system/fonts with the original filenames.

**Comment by LegacyEssentialOils** [comment]
Problems on 1.7 for me as well. System UI crashed upon installation of a font. It took about a minute for it to crash the system UI. During that time I was able to uninstall fontchanger to revert back to standard settings.

Whenever I didn't uninstall my system freaked out. Initially font worked though until the 1 minute was up and the system UI crashed.

I am running the newest version of magisk on a Moto z2 in Android 8.0 stock.

**Comment by DarkPreacher** [comment]
It worked for me after installation, I've tried several different fonts, Open Sans Condensed, Caprica and a few more. At first — everything was fine, fonts changed, but now — nothing happens, it looks like stock font all the time. I've restored to stock font, and tried again — no luck.
Font Changer v1.7(8)
OPPO Find 7, Lineage 16.0, Android 9
Busybox 1.30.1
Magisk 19.3

**Comment by yipinghuang1991** [comment]
@LegacyEssentialOils @DarkPreacher 
I uploaded a backup here. Try if it works.
[http://s000.tinyupload.com/?file_id=64868501783113376333](http://s000.tinyupload.com/?file_id=64868501783113376333)

**Comment by DarkPreacher** [comment]
@yipinghuang1991 
I've uninstalled all fonts related modules in Magisk, installed module from provided link, set something like ComicSans, to see changes for sure, rebooted and got a bootloop. I won't be playing with it any more, sorry.

**Comment by JohnFawkes** [comment]
there are betas in the telegram group. however i am working on 1.9 as we speak. sorry this didnt work for you guys but when 1.9 drops i encourage you guys to try it. ive fixed alot and the changelog is HUGE. in recent versions i was basically just replacing all font files and ive learned this will not work and thus the bootloops and crashes. ive learned what font file controls what and what the font xml file does. please try 1.9 when it comes out @DarkPreacher @yipinghuang1991 @LegacyEssentialOils

**Comment by DarkPreacher** [comment]
@JohnFawkes 
Thank you, will try 1.9 for sure, when it will be released.

**Comment by JohnFawkes** [comment]
new changelog
- revamped help menu. choose from main menu or use font_changer -h or font_changer -help
- new shortcuts options. 
Options:
    -s|—current                     show current font
    -l|—listc                     list custom fonts
    -a|—font [font name]         apply the font
    -d|—cfont [custom font]       apply the custom font
    -u|—update                           Update to latest beta
    -h|—help                          help
    -m|—list            list fonts <basically skips main menu>

- New colors to make certain things stand out more such as your current font
- bug fixes for things like choosing y on reboot no longer shows back to main menu.
- fix custom fonts (hopefully)
- start emoji support
- Better logging support. now will put everything i need to fix bugs into a tar.xz in the Fontchanger folder in internal storage. please send me this tar.xz if you encounter any bugs 
- added GNU sleep command compiled from source code. no more sleep invaild errors.
- added progress bar. now list loads faster. (will be applied to custom list in later update)
- Update feature. now you can use -u flag or —update to update to beta builds. no more searching telegram for the latest



heres the preview changelog for 1.9 @DarkPreacher

**Comment by JohnFawkes** [comment]
This has been fixed in v1.8. To watch the tutorial on how to use the custom option please see the 2 links to the video in the readme
