### ISSUE TITLE
Custom font not working 

### ISSUE THREAD

**Issue by madhub0815** [JohnFawkes/fontchanger#4]
Hello i am using a galaxy s9+ and Magisk 19.3.

I did the steps for the custom font. I can select it in terminal but it will not be installed correctly.
Seems like a permision problem?
I just put a TTF File in Folder named the same as the TTF folder as described. 

I attached the screenshot form terminal.
Can you have a loock? 
![Screenshot_20190803-114031_Material Terminal](https://user-images.githubusercontent.com/49038539/62410374-f4752680-b5e4-11e9-9850-2f28d3886d1d.jpg)

**Comment by JohnFawkes** [comment]
yes im aware of the issue. i will be redoing the custom part very soon. but only one font file is not going to work. i will be making a video on how to convert your single ttf file into the multiple files it will require. expect this very soon

**Comment by JohnFawkes** [comment]
This has been fixed in v1.8. To watch the tutorial on how to use the custom option please see the 2 links to the video in the readme
