### ISSUE TITLE
Crash when updating font changer from Magisk Manager, when i never ran the old version

### ISSUE THREAD

**Issue by jimbo1qaz** [JohnFawkes/fontchanger#5]
When the Magisk installation script detects it's upgrading an existing module, it runs `cp` on `/data/adb/modules/Fontchanger/*.txt`. But if I never ran fontchanger to create the file, the update script fails with "No such file or directory".

I think you should detect the absence of the file and skip backup/restore. Or maybe make backup/restore dependent on that file, not the module being installed. This will possibly cause uninstalling the module, rebooting, and installing the module restore settings (even if font changer is not installed).

**Comment by JohnFawkes** [comment]
> When the Magisk installation script detects it's upgrading an existing module, it runs `cp` on `/data/adb/modules/Fontchanger/*.txt`. But if I never ran fontchanger to create the file, the update script fails with "No such file or directory".
> 
> I think you should detect the absence of the file and skip backup/restore. Or maybe make backup/restore dependent on that file, not the module being installed. This will possibly cause uninstalling the module, rebooting, and installing the module restore settings (even if font changer is not installed).

This was fixed. Thanks
