### ISSUE TITLE
"No such file or directory" when applying font

### ISSUE THREAD

**Issue by KoenLust** [JohnFawkes/fontchanger#6]
Hi, I'm having a problem on my S8.
![Screenshot_20190905-020655_Terminal](https://user-images.githubusercontent.com/29061923/64302064-f2a2d800-cf81-11e9-9745-8a632e516172.png)
![IMG_20190905_021013](https://user-images.githubusercontent.com/29061923/64302160-5decaa00-cf82-11e9-9aa2-2ffc2fc74773.jpg)
I sort of understand what is going wrong here, but I do not have the knowledge of how to fix this. 
With my filemanager I can copy/paste the right files to the right place, so it's not completely broken.
Still wanted to share this because I really love the fonts and the simple interface! 
Keep up the good work! Peace ✌️

**Comment by soredake** [comment]
Same error with comicsans font.

**Comment by KoenLust** [comment]
I get this error with all the fonts

**Comment by rickidk** [comment]
Same thing with all the fonts and emojis
![Screenshot_20191205-104605_Material_Terminal](https://user-images.githubusercontent.com/58551463/70224472-9ea8ba80-174d-11ea-972c-adc048c5e3ad.png)

![Screenshot_20191205-105454_Impostazioni](https://user-images.githubusercontent.com/58551463/70224531-b3854e00-174d-11ea-9b98-0b951459d1e3.png)

**Comment by JohnFawkes** [comment]
should be fixed in latest 2.8.0.0
